sudo: required
language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - npm install -g typescript
  - pip install -U pip
  - pip install flake8
  - cd containers/datalab
  - ./build.sh
  - pip install selenium
  - sleep 2

script:
  - flake8 tools/cli/
  - cd containers/datalab
  - ./build.sh
  - python tools/test.py
