sudo: required
language: python
python:
- "2.7"

node_js:
- stable

services:
- docker

cache:
  pip: true
  directories:
  - $HOME/.docker/
  - node_modules

before_install:
- npm install -g typescript
- pip install -U pip
- pip install flake8

install:
- cd containers/test
- ./build.sh

script:
- cd ../../tools/
- flake8 cli/
- cd ../containers/test
- ./run.sh
