sudo: required
language: python
python:
- "2.7"

node_js:
- stable

services:
- docker

cache:
  pip: true
  directories:
  - $HOME/.docker/
  - node_modules

before_install:
- npm install -g typescript
- pip install -U pip
- pip install flake8 selenium pyyaml

install:
- cd containers/datalab
- ./build.sh
- ./run.sh test

before_script:
- cd ../../tools
- sleep 2

addons:
  sauce_connect:
    username: yelsayed
    access_key:
      secure: BSqBNn16UyZx2HcdCqTbq6Yr+WzbGcvfP5Q5+gKO4Fb3yc3XAcnqvIU/7GaiuKgmj3vQyUbUM7YswRjIKyb8cqpWVj6IE1iIVshYp6PjhyhX4PYcJt0IHJY+oEY4Pk0F7lVA4ScHWv2JsePd3ugLF4RBUGUWQsPRHoTmCC7VsOxG4BTNxi+qkFTHDLU4urFWPV5dTnzcsQN1V4GBZhnOcbgJTBOI4KCGpgbn3th9K+6hCJzViPPYnPaIjUFlsusGesxtcuyRPlNpOmH5uVHMjRLWSUsJ7uQxJWlMZ+qoM8czBzH0oyxJ5k1lCCgb7HMV1pAlSZaY1q3WPAu/TrV8Bh67CwieBsd9UCsucEW3mYw06SUMLFxMes47/atrhae3u/Bck1o1BiZC27CORE5BX9iYU3zBtM0DVcKvZt5/+B53qjc13rdyEnOH9Vjf8j0EMOAown48ydoUuTyJ8z+SjjywkSBa0GJKNp/2e0ycZUgaN2bsUja27Ad2Sb8r30rBMlIvPwg06Z1SQN3dUTLLU2lwiOkwna4p3ZeGi4x0bowSTmManW5m+5U+z4riLnjQeSVXoGppQcW+dnnFn1ka2y8Y3+rI9aSlc7D5mPYl9j4Cv/6bAfhV5IoN/WKnD/7ykIE0xPtg2rdB7ihaPAJPnxAiCwTKwnO7yVchXlnPckE=

script:
- flake8 cli/
- python test.py
