steps:
- name: 'debian'
  args: ['mkdir', '-p', '/workspace/containers/base/pydatalab']
  id:   'makeDir'

- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'ubuntu:16.04']
  id:   'pullUbuntu'
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'ubuntu:16.04', 'datalab-external-base-image']
  id:   'tagUbuntu'
  waitFor: ['pullUbuntu']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'datalab-base', '/workspace/containers/base/']
  id:   'buildBase'
  waitFor: ['makeDir', 'tagUbuntu']
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04']
  id:   'pullNvidiaUbuntu'
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04', 'datalab-external-base-image']
  id:   'tagNvidiaUbuntu'
  waitFor: ['buildBase', 'pullNvidiaUbuntu']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'datalab-core-gpu', '/workspace/containers/base/']
  id:   'buildGpuCore'
  waitFor: ['tagNvidiaUbuntu']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'datalab-base-gpu', '-f', '/workspace/containers/base/Dockerfile.gpu', '/workspace/containers/base/']
  id:   'buildGpuBase'
  waitFor: ['buildGpuCore']

- name: 'debian'
  args: ['/workspace/containers/datalab/prepare.sh', 'datalab-base', "${REVISION_ID}"]
  id:   'prepareDatalab'
  waitFor: ['buildBase']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/datalab:local-${REVISION_ID}', '/workspace/containers/datalab/']
  id:   'buildDatalab'
  waitFor: ['prepareDatalab']
- name: 'debian'
  args: ['/workspace/containers/datalab/cleanup.sh']
  id:   'cleanupDatalab'
  waitFor: ['buildDatalab']
- name: 'debian'
  args: ['/workspace/containers/datalab/prepare.sh', 'datalab-base-gpu', "${REVISION_ID}"]
  id:   'prepareDatalabGPU'
  waitFor: ['cleanupDatalab', 'buildGpuBase']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/datalab-gpu:local-${REVISION_ID}', '/workspace/containers/datalab/']
  id:   'buildDatalabGPU'
  waitFor: ['prepareDatalabGPU']

images:
  - 'gcr.io/${PROJECT_ID}/datalab:local-${REVISION_ID}'
  - 'gcr.io/${PROJECT_ID}/datalab-gpu:local-${REVISION_ID}'

timeout: '2400s'
