steps:
- name: 'debian'
  args: ['/workspace/sources/build.sh']
  id:   ['buildSource']
- name: 'debian'
  args: ['mkdir', '-p', '/workspace/containers/base/pydatalab']
  id:   ['makeDir']

- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'ubuntu:16.04']
  id:   'pullUbuntu'
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'ubuntu:16.04', 'datalab-external-base-image']
  id:   'tagUbuntu'
  waitFor: ['pullUbuntu']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'datalab-base', '/workspace/containers/base/']
  id:   'buildBase'
  waitFor: ['buildSource', 'makeDir', 'tagUbuntu']
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04']
  id:   'pullNvidiaUbuntu'
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04', 'datalab-external-base-image']
  id:   'tagNvidiaUbuntu'
  waitFor: ['buildBase']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'datalab-core-gpu', '/workspace/containers/base/']
  id:   'buildGpuCore'
  waitFor: ['tagNvidiaUbuntu']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'datalab-base-gpu', '-f', 'Dockerfile.gpu', '/workspace/containers/base/']
  id:   'buildGpuBase'
  waitFor: ['buildGpuCore']
